const t = [{
    show:true,
    number:1,
    Mat:18000,
    adm:'01/11/2016',
    CPF:'123.345.678-9',
    residencia:'Macaé',
    VT:'VT MACAÉ',
    nasc: '29/04/1985',
    ASO: '08/11/2020',
    setor:'OFICINA',
    regime:'180,00',
    salario:{
        base:1239.12,
        maior: 1239.12
    },
    NOT:'',
    PER:'',
    HT: '',
    ferias:true,
    user:"Joao da Silva",
    job: "Técnico de Alguma Coisa",
    status:['TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT']
},
{
    show:true,
    number:2,
    Mat:18320,
    adm:'01/01/2016',
    CPF:'123.345.678-9',
    residencia:'Rio das Ostras',
    VT:'SEM VT',
    nasc: '29/04/1990',
    ASO: '08/10/2020',
    setor:'OFICINA',
    regime:'175,00',
    salario:{
        base:1230.12,
        maior: 1230.12
    },
    NOT:'',
    PER:'',
    HT: '',
    ferias:true,
    user:"Maria das Dores",
    job: "Técnico de Outra Coisa",
    status:['CC','AT','AT','ST','TT','TT','TT','CC','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','CC','CC','AT','AT','BT','TT','TT','TT','AT','ST','AT','BT','TT']
},{
    show:true,
    number:1,
    Mat:18000,
    adm:'01/11/2016',
    CPF:'123.345.678-9',
    residencia:'Macaé',
    VT:'VT MACAÉ',
    nasc: '29/04/1985',
    ASO: '08/11/2020',
    setor:'OFICINA',
    regime:'180,00',
    salario:{
        base:1239.12,
        maior: 1239.12
    },
    NOT:'',
    PER:'',
    HT: '',
    ferias:true,
    user:"Joao da Silva",
    job: "Técnico de Alguma Coisa",
    status:['TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT']
},
{
    show:true,
    number:2,
    Mat:18320,
    adm:'01/01/2016',
    CPF:'123.345.678-9',
    residencia:'Rio das Ostras',
    VT:'SEM VT',
    nasc: '29/04/1990',
    ASO: '08/10/2020',
    setor:'OFICINA',
    regime:'175,00',
    salario:{
        base:1230.12,
        maior: 1230.12
    },
    NOT:'',
    PER:'',
    HT: '',
    ferias:true,
    user:"Maria das Dores",
    job: "Técnico de Outra Coisa",
    status:['CC','AT','AT','ST','TT','TT','TT','CC','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','CC','CC','AT','AT','BT','TT','TT','TT','AT','ST','AT','BT','TT']
},{
    show:true,
    number:1,
    Mat:18000,
    adm:'01/11/2016',
    CPF:'123.345.678-9',
    residencia:'Macaé',
    VT:'VT MACAÉ',
    nasc: '29/04/1985',
    ASO: '08/11/2020',
    setor:'OFICINA',
    regime:'180,00',
    salario:{
        base:1239.12,
        maior: 1239.12
    },
    NOT:'',
    PER:'',
    HT: '',
    ferias:true,
    user:"Joao da Silva",
    job: "Técnico de Alguma Coisa",
    status:['TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT']
},
{
    show:true,
    number:2,
    Mat:18320,
    adm:'01/01/2016',
    CPF:'123.345.678-9',
    residencia:'Rio das Ostras',
    VT:'SEM VT',
    nasc: '29/04/1990',
    ASO: '08/10/2020',
    setor:'OFICINA',
    regime:'175,00',
    salario:{
        base:1230.12,
        maior: 1230.12
    },
    NOT:'',
    PER:'',
    HT: '',
    ferias:true,
    user:"Maria das Dores",
    job: "Técnico de Outra Coisa",
    status:['CC','AT','AT','ST','TT','TT','TT','CC','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','CC','CC','AT','AT','BT','TT','TT','TT','AT','ST','AT','BT','TT']
},{
    show:true,
    number:1,
    Mat:18000,
    adm:'01/11/2016',
    CPF:'123.345.678-9',
    residencia:'Macaé',
    VT:'VT MACAÉ',
    nasc: '29/04/1985',
    ASO: '08/11/2020',
    setor:'OFICINA',
    regime:'180,00',
    salario:{
        base:1239.12,
        maior: 1239.12
    },
    NOT:'',
    PER:'',
    HT: '',
    ferias:true,
    user:"Joao da Silva",
    job: "Técnico de Alguma Coisa",
    status:['TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT']
},
{
    show:true,
    number:2,
    Mat:18320,
    adm:'01/01/2016',
    CPF:'123.345.678-9',
    residencia:'Rio das Ostras',
    VT:'SEM VT',
    nasc: '29/04/1990',
    ASO: '08/10/2020',
    setor:'OFICINA',
    regime:'175,00',
    salario:{
        base:1230.12,
        maior: 1230.12
    },
    NOT:'',
    PER:'',
    HT: '',
    ferias:true,
    user:"Maria das Dores",
    job: "Técnico de Outra Coisa",
    status:['CC','AT','AT','ST','TT','TT','TT','CC','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','CC','CC','AT','AT','BT','TT','TT','TT','AT','ST','AT','BT','TT']
},{
    show:true,
    number:1,
    Mat:18000,
    adm:'01/11/2016',
    CPF:'123.345.678-9',
    residencia:'Macaé',
    VT:'VT MACAÉ',
    nasc: '29/04/1985',
    ASO: '08/11/2020',
    setor:'OFICINA',
    regime:'180,00',
    salario:{
        base:1239.12,
        maior: 1239.12
    },
    NOT:'',
    PER:'',
    HT: '',
    ferias:true,
    user:"Joao da Silva",
    job: "Técnico de Alguma Coisa",
    status:['TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT']
},
{
    show:true,
    number:2,
    Mat:18320,
    adm:'01/01/2016',
    CPF:'123.345.678-9',
    residencia:'Rio das Ostras',
    VT:'SEM VT',
    nasc: '29/04/1990',
    ASO: '08/10/2020',
    setor:'OFICINA',
    regime:'175,00',
    salario:{
        base:1230.12,
        maior: 1230.12
    },
    NOT:'',
    PER:'',
    HT: '',
    ferias:true,
    user:"Maria das Dores",
    job: "Técnico de Outra Coisa",
    status:['CC','AT','AT','ST','TT','TT','TT','CC','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','CC','CC','AT','AT','BT','TT','TT','TT','AT','ST','AT','BT','TT']
},{
    show:true,
    number:1,
    Mat:18000,
    adm:'01/11/2016',
    CPF:'123.345.678-9',
    residencia:'Macaé',
    VT:'VT MACAÉ',
    nasc: '29/04/1985',
    ASO: '08/11/2020',
    setor:'OFICINA',
    regime:'180,00',
    salario:{
        base:1239.12,
        maior: 1239.12
    },
    NOT:'',
    PER:'',
    HT: '',
    ferias:true,
    user:"Joao da Silva",
    job: "Técnico de Alguma Coisa",
    status:['TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT']
},
{
    show:true,
    number:2,
    Mat:18320,
    adm:'01/01/2016',
    CPF:'123.345.678-9',
    residencia:'Rio das Ostras',
    VT:'SEM VT',
    nasc: '29/04/1990',
    ASO: '08/10/2020',
    setor:'OFICINA',
    regime:'175,00',
    salario:{
        base:1230.12,
        maior: 1230.12
    },
    NOT:'',
    PER:'',
    HT: '',
    ferias:true,
    user:"Maria das Dores",
    job: "Técnico de Outra Coisa",
    status:['CC','AT','AT','ST','TT','TT','TT','CC','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','CC','CC','AT','AT','BT','TT','TT','TT','AT','ST','AT','BT','TT']
},{
    show:true,
    number:1,
    Mat:18000,
    adm:'01/11/2016',
    CPF:'123.345.678-9',
    residencia:'Macaé',
    VT:'VT MACAÉ',
    nasc: '29/04/1985',
    ASO: '08/11/2020',
    setor:'OFICINA',
    regime:'180,00',
    salario:{
        base:1239.12,
        maior: 1239.12
    },
    NOT:'',
    PER:'',
    HT: '',
    ferias:true,
    user:"Joao da Silva",
    job: "Técnico de Alguma Coisa",
    status:['TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','AT','BT','TT']
},
{
    show:true,
    number:2,
    Mat:18320,
    adm:'01/01/2016',
    CPF:'123.345.678-9',
    residencia:'Rio das Ostras',
    VT:'SEM VT',
    nasc: '29/04/1990',
    ASO: '08/10/2020',
    setor:'OFICINA',
    regime:'175,00',
    salario:{
        base:1230.12,
        maior: 1230.12
    },
    NOT:'',
    PER:'',
    HT: '',
    ferias:true,
    user:"Maria das Dores",
    job: "Técnico de Outra Coisa",
    status:['CC','AT','AT','ST','TT','TT','TT','CC','AT','BT','TT','TT','TT','CC','CC','AT','AT','ST','CC','CC','AT','AT','BT','TT','TT','TT','AT','ST','AT','BT','TT']
}]